---
dependencies: []

galaxy_info:
  author: <name>
  description: Install multiple instances of flask apps on linux with nginx
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
  - name: Ubuntu
    versions:
      - bionic
  galaxy_tags:
    - web
